#!/bin/bash
set -e
# =============================================================
#  pywal + Kvantum + qt6ct setup
# =============================================================

source "./utils.sh"

WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
WAL_TEMPLATES="$HOME/.config/wal/templates"
KVANTUM_PYWAL="$HOME/.config/Kvantum/pywal"
QT6CT_COLORS="$HOME/.config/qt6ct/colors"
QT6CT_CONF="$HOME/.config/qt6ct/qt6ct.conf"
HYPR_SCRIPT_DIR="$HOME/.config/hypr/Trist4nScript"
kitty_conf="$HOME/.config/kitty/kitty.conf"

log_step "Creation of folders..."
mkdir -p "$WALLPAPER_DIR"
mkdir -p "$WAL_TEMPLATES"
mkdir -p "$KVANTUM_PYWAL"
mkdir -p "$QT6CT_COLORS"
mkdir -p "$HYPR_SCRIPT_DIR"

# -------------------------------------------------------------
# Template Kvantum SVG for pywal
# -------------------------------------------------------------
log_step "Installation des templates pywal"
if [ -f "$WAL_TEMPLATES/pywal.svg" ]; then
    log_info "Existing templates, skip."
else
    log_info "Copy assets/pywal.svg and assets/pywal.kvconfig in $WAL_TEMPLATES"
    cp ./assets/kvantum/pywal.svg $WAL_TEMPLATES
    cp ./assets/kvantum/pywal.kvconfig $WAL_TEMPLATES
fi

# -------------------------------------------------------------
# Template qt6ct for pywal
# -------------------------------------------------------------
log_step "Creation qt6ct template..."
cp ./assets/qt/colors-qt6ct.conf $WAL_TEMPLATES

# -------------------------------------------------------------
# Symlink qt6ct/Kvantum colors → cache wal
# -------------------------------------------------------------
log_step "Symlink qt6ct colors..."
ln -sf "$HOME/.cache/wal/colors-qt6ct.conf" "$QT6CT_COLORS/pywal.conf"
log_step "Symlink Kvantum colors..."
ln -sf "$HOME/.cache/wal/pywal.svg" "$KVANTUM_PYWAL/pywal.svg"
ln -sf "$HOME/.cache/wal/pywal.kvconfig" "$KVANTUM_PYWAL/pywal.kvconfig"

# -------------------------------------------------------------
# Config qt6ct
# -------------------------------------------------------------
log_step "Configuration qt6ct..."
if [ -f "$QT6CT_CONF" ]; then
    sed -i 's|color_scheme_path=.*|color_scheme_path=/home/'"$USER"'/.config/qt6ct/colors/pywal.conf|' "$QT6CT_CONF"
    sed -i 's/custom_palette=false/custom_palette=true/' "$QT6CT_CONF"
    log_success "Options have been added to $QT6CT_CONF file."
else
    mkdir -p "$(dirname "$QT6CT_CONF")"
    cp ./assets/qt6ct.conf $QT6CT_CONF
    log_success "A new $QT6CT_CONF file has been created."
fi

# -------------------------------------------------------------
# Env Variables Qt in hyprland
# -------------------------------------------------------------
log_step "Checking the Qt environment variables in Hyprland..."
HYPR_CONF="$HOME/.config/hypr/hyprland.lua"
if [ -f "$HYPR_CONF" ]; then
    if ! grep -q "QT_QPA_PLATFORMTHEME" "$HYPR_CONF"; then
        echo "-- Qt theming" >> "$HYPR_CONF"
        echo "hl.env(\"QT_QPA_PLATFORMTHEME\", \"qt6ct\")" >> "$HYPR_CONF"
        log_success "Options have been added  to hyprland.conf"
    else
        log_info "Already present in hyprland.lua"
    fi
else
    log_warn "hyprland.lua not found, add manually: ${BOLD}hl.env(\"QT_QPA_PLATFORMTHEME\", \"qt6ct\")${NC}"
fi

# -------------------------------------------------------------
# Install "theme-switch.sh"
# -------------------------------------------------------------
log_step "Install theme-switch.sh script..."
cp "$(dirname "$0")/scripts/theme-switch.sh" "$HYPR_SCRIPT_DIR/" || true
chmod +x "$HYPR_SCRIPT_DIR/theme-switch.sh" || true

# -------------------------------------------------------------
# Kitty Theme
# -------------------------------------------------------------
log_step "Colors in Kitty terminal"
if ask_yes_no "Do you want to configure Kitty?"; then
    if ! grep -q "colors-kitty.conf" "$kitty_conf"; then
        echo -e "\n# Include the colors generated by Pywal\ninclude ~/.cache/wal/colors-kitty.conf" >> "$kitty_conf"
        log_success "Kitty configured successfully."
    else
        log_info "Kitty already configured."
    fi
else
    log_info "Skipping Kitty configuration."
fi

# -------------------------------------------------------------
# Setup Complete
# -------------------------------------------------------------
echo ""
echo "✅ Pywal Setup complete!"
echo ""
echo "Remaining manual checklist:"
echo " 1. Copy your wallpapers to $WALLPAPER_DIR"
echo " 2. Run "$HYPR_SCRIPT_DIR/theme-switch.sh" to test"
echo " 3. Add a keyboard shortcut to switch themes --> \"hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("sh ~/.config/hypr/Trist4nScript/theme-switch.sh"))\""
