#!/bin/bash
# =============================================================
#  pywal + Kvantum + qt6ct setup
# =============================================================
set -e
source "./utils.sh"

wallpaper_dir="$HOME/Pictures/Wallpapers"
wal_templates="$HOME/.config/wal/templates"
kvantum_pywal="$HOME/.config/Kvantum/pywal"
qt6ct_colors="$HOME/.config/qt6ct/colors"
qt6ct_conf="$HOME/.config/qt6ct/qt6ct.conf"
hypr_conf="$HOME/.config/hypr/hyprland.lua"
hypr_script_dir="$HOME/.config/hypr/Trist4nScript"
kitty_conf="$HOME/.config/kitty/kitty.conf"

log_step "Creation of folders..."
mkdir -p "$wallpaper_dir"
mkdir -p "$wal_templates"
mkdir -p "$kvantum_pywal"
mkdir -p "$qt6ct_colors"
mkdir -p "$hypr_script_dir"

# -------------------------------------------------------------
# Template Kvantum SVG for pywal
# -------------------------------------------------------------
log_step "Installation des templates pywal"
if [ -f "$wal_templates/pywal.svg" ]; then
    log_info "Existing templates, skip."
else
    log_info "Copy assets/pywal.svg and assets/pywal.kvconfig in $wal_templates"
    cp ./assets/kvantum/pywal.svg $wal_templates
    cp ./assets/kvantum/pywal.kvconfig $wal_templates
fi

# -------------------------------------------------------------
# Template qt6ct for pywal
# -------------------------------------------------------------
log_step "Creation qt6ct template..."
cp ./assets/qt/colors-qt6ct.conf $wal_templates

# -------------------------------------------------------------
# Symlink qt6ct/Kvantum colors → cache wal
# -------------------------------------------------------------
log_step "Symlink qt6ct colors..."
ln -sf "$HOME/.cache/wal/colors-qt6ct.conf" "$qt6ct_colors/pywal.conf"
log_step "Symlink Kvantum colors..."
ln -sf "$HOME/.cache/wal/pywal.svg" "$kvantum_pywal/pywal.svg"
ln -sf "$HOME/.cache/wal/pywal.kvconfig" "$kvantum_pywal/pywal.kvconfig"

# -------------------------------------------------------------
# Config qt6ct
# -------------------------------------------------------------
log_step "Configuration qt6ct..."
if [ -f "$qt6ct_conf" ]; then
    sed -i 's|color_scheme_path=.*|color_scheme_path=/home/'"$USER"'/.config/qt6ct/colors/pywal.conf|' "$qt6ct_conf"
    sed -i 's/custom_palette=false/custom_palette=true/' "$qt6ct_conf"
    log_success "Options have been added to $qt6ct_conf file."
else
    mkdir -p "$(dirname "$qt6ct_conf")"
    cp ./assets/qt6ct.conf $qt6ct_conf
    log_success "A new $qt6ct_conf file has been created."
fi

# -------------------------------------------------------------
# Env Variables Qt in hyprland
# -------------------------------------------------------------
log_step "Checking the Qt environment variables in Hyprland..."
if [ -f "$hypr_conf" ]; then
    if ! grep -q "QT_QPA_PLATFORMTHEME" "$hypr_conf"; then
        echo "-- Qt theming" >> "$hypr_conf"
        echo "hl.env(\"QT_QPA_PLATFORMTHEME\", \"qt6ct\")" >> "$hypr_conf"
        log_success "Options have been added  to hyprland.conf"
    else
        log_info "Already present in hyprland.lua"
    fi
else
    log_warn "hyprland.lua not found, add manually: ${BOLD}hl.env(\"QT_QPA_PLATFORMTHEME\", \"qt6ct\")${NC}"
fi

# -------------------------------------------------------------
# Install "theme-switch.sh"
# -------------------------------------------------------------
log_step "Install theme-switch.sh script..."
cp "$(dirname "$0")/scripts/theme-switch.sh" "$hypr_script_dir/" || true
chmod +x "$hypr_script_dir/theme-switch.sh" || true

# -------------------------------------------------------------
# Kitty Theme
# -------------------------------------------------------------
log_step "Colors in Kitty terminal"
if ask_yes_no "Do you want to configure Kitty?"; then
    if ! grep -q "colors-kitty.conf" "$kitty_conf"; then
        echo -e "\n# Include the colors generated by Pywal\ninclude ~/.cache/wal/colors-kitty.conf" >> "$kitty_conf"
        log_success "Kitty configured successfully."
    else
        log_info "Kitty already configured."
    fi
else
    log_info "Skipping Kitty configuration."
fi

echo ""
echo "🎉 Pywal Setup complete!"
echo ""
echo "Remaining manual checklist:"
echo " 1. Copy your wallpapers to $wallpaper_dir"
echo " 2. Run "$hypr_script_dir/theme-switch.sh" to test"
echo -e " 3. Add a keyboard shortcut to switch themes --> ${BLUE}${BOLD}\"hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("sh ~/.config/hypr/Trist4nScript/theme-switch.sh"))\"${NC}"
echo ""