# Source Pywal colors
source = ~/.cache/wal/colors-hyprland.conf

# Global Font Variable
$font = JetBrainsMono Nerd Font

background {
    monitor =
    path = screenshot
    color = $color0
    blur_passes = 3
    blur_size = 3
    noise = 0.02
    contrast = 0.9
    brightness = 0.50
    vibrancy = 0.15
    vibrancy_darkness = 0.2
}

# Weather Icon
label {
    monitor =
    text = cmd[update:600000] echo "<span>$(~/.config/hyprland-setup/scripts/weather.sh icon)  </span>"
    color = $color4
    font_size = 34
    font_family = $font Bold
    position = -180, -48
    halign = right
    valign = top
}

# Weather Temperature
label {
    monitor =
    text = cmd[update:600000] ~/.config/hyprland-setup/scripts/weather.sh temp
    color = $color7
    font_size = 34
    font_family = $font Bold
    position = -48, -48
    halign = right
    valign = top
}

# Weather Description
label {
    monitor =
    text = cmd[update:600000] ~/.config/hyprland-setup/scripts/weather.sh desc
    color = $foreground
    font_size = 12
    font_family = $font Bold
    position = -48, -110
    halign = right
    valign = top
}

# Weather Wind
label {
    monitor =
    text = cmd[update:600000] echo " $(~/.config/hyprland-setup/scripts/weather.sh wind)"
    color = $foreground
    font_size = 12
    font_family = $font Bold
    position = -48, -130
    halign = right
    valign = top
}

# Weather City
label {
    monitor =
    text = cmd[update:0] ~/.config/hyprland-setup/scripts/weather.sh city
    color = $color4
    font_size = 11
    font_family = $font Bold
    position = -48, -150
    halign = right
    valign = top
}

# Clock
label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 96
    font_family = $font Bold
    position = 96, 40
    halign = left
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] LC_TIME=en_US.UTF-8 date +"%A, %B %d, %Y"
    color = $foreground
    font_size = 18
    font_family = $font
    position = 96, -40
    halign = left
    valign = center
}

input-field {
    monitor =
    size = 284, 44
    outline_thickness = 1
    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    outer_color = $color4
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = $foreground
    font_family = $font
    check_color = $color2
    fail_color = $color1
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = Password...
    hide_input = false
    rounding = 8
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:0] hostname
    color = $foreground
    font_size = 11
    font_family = $font
    position = 36, 36
    halign = left
    valign = bottom
}
