import QtQuick
pragma Singleton

QtObject {
    // Basic System Icons
    readonly property string clean: "󰃢"
    readonly property string cross: "󰅖"
    readonly property string calendar: "󰃭"
    readonly property string music: "󰝚"
    readonly property string musicOff: "󰝛"
    readonly property string wifi: "󰖩"
    readonly property string wifiAlert: "󱚵"
    readonly property string bluetooth: "󰂯"
    readonly property string bluetoothConnect: "󰂱"
    readonly property string bluetoothOff: "󰂲"
    readonly property string notification: "󰂜"
    readonly property string notificationOff: "󰪑"
    readonly property string setting: ""
    readonly property string volumeLow: "󰕿"
    readonly property string volumeMedium: "󰖀"
    readonly property string volume: "󰕾"
    readonly property string volumeOff: "󰝟"
    readonly property string mic: "󰍬"
    readonly property string micOff: "󰍭"
    readonly property string skipPrevious: "󰼨"
    readonly property string skipNext: "󰼧"
    readonly property string pause: "󰏤"
    readonly property string play: "󰐊"
    readonly property string check: "✓"
    readonly property string chevronRight: ""
    // App Icons
    readonly property string defaultIcon: ""
    readonly property string browser: ""
    readonly property string code: ""
    readonly property string terminal: "󰆍"
    readonly property string folder: ""
    readonly property string discord: ""
    readonly property string media: "󰕼"
    readonly property string settingsAlt: "󰒓"
    readonly property string bluetoothManager: ""
    readonly property string audioControl: "󱕂"
    readonly property string networkManager: "󰐻"
    readonly property string productivity: ""
    readonly property string thunderbird: ""
    readonly property string mail: "󰶊"
}
